### PR TITLE
Rspec tests

### PR DESCRIPTION
**Pull request by alvp01**
# Milestone 1
- Added tests for all methods inside the tic-tac-toe game

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets edit this pull request, you are to use Gitflow for this project  
- [x] Lets write test for the method in `Player` class
- [x] Lets test for  a draw scenario between players.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by uryelah** [comment]
Hi **Abel Lavieri & Michael Threels**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job testing your game thoroughly! 

You are just missing adding the testing info to your readme file, then you'll be ready for bigger and better projects! 💪 

# Required Changes 🏗️ 🐛 💡

- [ ] Add a testing or test section to your readme file with instructions on running tests.

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by whiz25 — APPROVED** [review]
## Congratulations :clap:
The required changes have been made. Let's merge and proceed to the next project.

### Martin Afani

**Comment by alvp01** [comment]
> ## Congratulations 
> The required changes have been made. Let's merge and proceed to the next project.
> 
> ### Martin Afani

Thanks for your time. Happy weekend

**Pull request merged**
