### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by alvp01**
### *Changes made in this branch*
- Adding the game logic and win conditions to the game.
- Improving the game flow
- Moved some methods from some classes to the main file

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team. 👋

**Great game you created here.🚀**
👍 @alvp01  and @simandebvu 

However lets fix these:

- [x] Kindly consider removing the `Live Demo link` in your readme as it doesn't lead anywhere. However you can consider adding your game to a service like [repl.it](https://repl.it/) and then update the live demo link with the repl.it game link.

- [x] On running your game if i input a board number that has already been filled, it shows the output `Remember to enter a number between 1 and 9` perhaps rather you can consider letting the user know that that board position has been filled up.

- [x] In your String class on lib folder there are 6 methods(magenta, brown, blue, gray, black and cyan) which you didn't end up using, consider removing the redundant methods or use them in your `bin/main.rb` file.

**Overall good code flow and good application of a method having a single responsibility.**🚀

Simply fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification, i'll gladly reply.🙂

HAPPY CODING👨‍💻

**Comment by simandebvu** [comment]
## Changes made
- Prompt if a number already entered.
- Live link removed (Will be added in Milestone 4).
- Removed redundant methods.

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great work, congratulation :+1: Milestone Approved.
You did all changes required previously. Go ahead and merge to develop.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
