### PR TITLE
Feature user interface

### PR DESCRIPTION
**Pull request by simandebvu**
## Added 

- Basic User Interface

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @simandebvu and @alvp01 :clap: 
#### You have done a good but there are some requirements missing (or you didn't consider) in your implementation. Check the following Basic game flow: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)) and try to indicate how you thought about everything listed below in your implementation.

* [x] `[OPTIONAL]` game asks players for their names
* [x] `[REQUIRED]` game tells which player turn it is
* [x] `[REQUIRED]` game asks the player to select from available moves
* [x] `[REQUIRED]` game informs player if the selected move is invalid
* [x] `[REQUIRED]` game displays board after the player move
* [x] `[REQUIRED]` game informs player if the selected move is a winning move
* [x] `[REQUIRED]` game informs player if the selected move is a draw move
* [x] `[REQUIRED]` game repeats all actions for the next player's move

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Review by davidmrtz-dev — APPROVED** [review]
### **Status: Approved.** ✅ 
****
### Hi Team. 😄 
****
Great Job 💯 👍  @simandebvu @alvp01  , You correctly implemented all the specifications.
You can merge this branch and move onto the next project. 🎊
Congrats for the good readme 👏 .
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by alvp01** [comment]
Thanks, @davitomix!
If there is any suggestion about how could we improve the code would also be very welcome.

**Pull request merged**
